name: Build and Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main  # Trigger only on main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: flasksreapp           # ✅ Your Azure Web App name (from your screenshot)
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
